#!/usr/bin/env node
import crypto from 'node:crypto';
import dgram from 'node:dgram';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';
import {execFileSync} from 'node:child_process';
import {EventEmitter} from 'node:events';

export const POLICIES={go:['native',65536,64],rust:['native',65536,64],zig:['native',32768,64],ada:['native',448,32],d:['native',1200,32],nim:['native',16384,64],cpp:['native',32768,64],pony:['native',960,32],hare:['native',896,16],carp:['native',960,16],gleam:['native',4096,32],idris:['native',1024,32]};
const MAGIC=Buffer.from('S6NA'), VERSION=1, DATA=1, ACK=2, EXTENSION=3, HEADER=32, TAG=16;
export const DEFAULT_LIMITS=Object.freeze({max_message:16*1024*1024,max_streams:64,max_inflight:16*1024*1024,max_window:64,reassembly_seconds:30,max_extensions:16,payload_bytes:0,window_frames:0});
export function validateLimits(input={}){let allowed=new Set(Object.keys(DEFAULT_LIMITS));if(!input||Array.isArray(input)||typeof input!=='object'||Object.keys(input).some(k=>!allowed.has(k)))throw Error('unknown S6NA limit');let x=Object.freeze({...DEFAULT_LIMITS,...input}),bounds={max_message:[1024,256*1024*1024],max_streams:[1,4096],max_inflight:[1024,512*1024*1024],max_window:[1,4096],reassembly_seconds:[1,300],max_extensions:[0,128],payload_bytes:[0,65536],window_frames:[0,4096]};for(let [k,[a,b]] of Object.entries(bounds))if(!Number.isSafeInteger(x[k])||x[k]<a||x[k]>b)throw Error(`${k} is outside safe bounds`);if(x.max_inflight<x.max_message||x.payload_bytes>0&&x.payload_bytes<64)throw Error('inconsistent S6NA limits');return x}
export function loadLimits(configPath){if(configPath===undefined)return validateLimits();let before=fs.lstatSync(configPath,{bigint:true});if(!before.isFile()||before.isSymbolicLink()||before.uid!==BigInt(process.geteuid())||before.size>16384n)throw Error('configuration must be a bounded owned regular file');let fd=fs.openSync(configPath,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW|(fs.constants.O_CLOEXEC||0));try{let opened=fs.fstatSync(fd,{bigint:true}),data=Buffer.alloc(16385),count=fs.readSync(fd,data,0,data.length,0),after=fs.fstatSync(fd,{bigint:true}),same=(a,b)=>['dev','ino','size','mode','uid','nlink','mtimeNs','ctimeNs'].every(k=>a[k]===b[k]);if(!same(before,opened)||!same(opened,after)||count>16384)throw Error('configuration changed while reading');let value=JSON.parse(data.subarray(0,count).toString('utf8'));if(!value||Array.isArray(value)||Object.keys(value).sort().join(',')!=='limits,schema'||value.schema!=='shadow6.s6na-limits.v1')throw Error('unknown S6NA limits schema or field');return validateLimits(value.limits)}finally{fs.closeSync(fd)}}
function derive(key,direction){return crypto.createHmac('sha256',key).update(Buffer.concat([Buffer.from('shadow6-network-v1:'),Buffer.from([direction])])).digest()}
function nonce(header){return crypto.createHash('sha256').update('shadow6-network-nonce-v1').update(header).digest().subarray(0,12)}
function portable(value,depth=0){if(depth>8)throw Error('extension nesting exceeds 8');if(value===null||typeof value==='boolean')return;if(typeof value==='string'){if(Buffer.byteLength(value)>1024)throw Error('extension string is oversized');return}if(typeof value==='number'){if(!Number.isSafeInteger(value))throw Error('extension integer is not portable');return}if(Array.isArray(value)){if(value.length>64)throw Error('extension array is oversized');value.forEach(x=>portable(x,depth+1));return}if(typeof value==='object'){let keys=Object.keys(value);if(keys.length>64)throw Error('extension object is oversized');keys.forEach(k=>{portable(k,depth+1);portable(value[k],depth+1)});return}throw Error('extension contains a nonportable value')}
function canonical(value){portable(value);let sort=x=>Array.isArray(x)?x.map(sort):(x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x);let out=Buffer.from(JSON.stringify(sort(value)));if(out.length>4096)throw Error('extension payload exceeds 4 KiB');return out}
export function loadKey(keyPath){
 if(process.platform==='win32'){
  const shell=path.join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe');
  const result=execFileSync(shell,['-NoLogo','-NoProfile','-NonInteractive','-File',
   fileURLToPath(new URL('./secure_key_windows.ps1',import.meta.url)),
   '-Operation','read','-KeyPath',path.resolve(keyPath)],{timeout:30000,maxBuffer:65536,windowsHide:true});
  if(!/^[A-Za-z0-9+/]{43}=$/.test(result.toString('ascii')))throw Error('invalid secure key response');
  return Buffer.from(result.toString('ascii'),'base64');
 }
 const before=fs.lstatSync(keyPath,{bigint:true});
 if(!before.isFile()||before.isSymbolicLink()||before.uid!==BigInt(process.geteuid())||
    (before.mode&0o777n)!==0o600n||before.size!==32n)throw Error('adapter key must be an owned 32-byte mode-0600 regular file');
 const same=(a,b)=>['dev','ino','size','mode','uid','nlink','mtimeNs','ctimeNs'].every(k=>a[k]===b[k]);
 const fd=fs.openSync(keyPath,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW|(fs.constants.O_CLOEXEC||0));
 try{
  const opened=fs.fstatSync(fd,{bigint:true});
  if(!same(before,opened))throw Error('adapter key changed while opening');
  const data=Buffer.alloc(33),count=fs.readSync(fd,data,0,33,0),after=fs.fstatSync(fd,{bigint:true});
  if(count!==32||!same(opened,after))throw Error('adapter key changed while reading');
  return data.subarray(0,32);
 }finally{fs.closeSync(fd)}
}
export class Codec{
 constructor(key,payload,side=0,maxStreams=64){if(!Buffer.isBuffer(key)||key.length!==32)throw Error('adapter key must be 32 bytes');if(!Number.isInteger(payload)||payload<64||payload>65536)throw Error('invalid adapter payload');if(side!==0&&side!==1)throw Error('invalid side');if(!Number.isInteger(maxStreams)||maxStreams<1||maxStreams>4096)throw Error('invalid stream limit');this.tx=derive(key,side);this.rx=derive(key,1-side);this.payload=payload;this.maxStreams=maxStreams}
 encode(kind,stream,message,index,count,payload=Buffer.alloc(0)){if(![DATA,ACK,EXTENSION].includes(kind)||!Number.isInteger(stream)||stream<0||stream>=this.maxStreams||message<0n||message>0xffffffffffffffffn)throw Error('invalid frame identity');if(!Buffer.isBuffer(payload)||payload.length>this.payload||count<1||count>65535||index<0||index>=count)throw Error('invalid frame bounds');let h=Buffer.alloc(HEADER);MAGIC.copy(h);h.writeUInt8(VERSION,4);h.writeUInt8(kind,5);h.writeBigUInt64BE(BigInt(stream),8);h.writeBigUInt64BE(message,16);h.writeUInt16BE(index,24);h.writeUInt16BE(count,26);h.writeUInt32BE(payload.length,28);let c=crypto.createCipheriv('chacha20-poly1305',this.tx,nonce(h),{authTagLength:16});c.setAAD(h,{plaintextLength:payload.length});let body=Buffer.concat([c.update(payload),c.final(),c.getAuthTag()]);return Buffer.concat([h,body])}
 decode(wire){if(!Buffer.isBuffer(wire)||wire.length<HEADER+TAG||wire.length>HEADER+this.payload+TAG)throw Error('invalid frame size');let h=wire.subarray(0,HEADER),kind=h[5],stream=h.readBigUInt64BE(8),message=h.readBigUInt64BE(16),index=h.readUInt16BE(24),count=h.readUInt16BE(26),length=h.readUInt32BE(28);if(!h.subarray(0,4).equals(MAGIC)||h[4]!==VERSION||h.readUInt16BE(6)!==0||![DATA,ACK,EXTENSION].includes(kind)||length!==wire.length-HEADER-TAG||stream>=BigInt(this.maxStreams)||count<1||index>=count)throw Error('invalid frame header');let body=wire.subarray(HEADER,-TAG),tag=wire.subarray(-TAG),d=crypto.createDecipheriv('chacha20-poly1305',this.rx,nonce(h),{authTagLength:16});d.setAAD(h,{plaintextLength:body.length});d.setAuthTag(tag);let payload;try{payload=Buffer.concat([d.update(body),d.final()])}catch{throw Error('frame authentication failed')}if(kind===ACK&&payload.length)throw Error('invalid acknowledgment');return {kind,stream:Number(stream),message,index,count,payload}}
}
export class ReliableAdapter{
 constructor(core,key,side=0,extensions=[],limits={},clock=()=>performance.now()/1000){if(!(core in POLICIES))throw Error('unknown core');this.clock=clock;this.limits=validateLimits(limits);this.policy=POLICIES[core];this.codec=new Codec(key,this.limits.payload_bytes||this.policy[1],side,this.limits.max_streams);this.extensions=new Set(extensions);if(this.extensions.size!==extensions.length||this.extensions.size>this.limits.max_extensions||extensions.some(x=>typeof x!=='string'||x.length<1||x.length>64))throw Error('invalid extension allowlist');this.next=Array(this.limits.max_streams).fill(0n);this.pending=new Map();this.outgoing=new Map();this.queues=Array.from({length:this.limits.max_streams},()=>[]);this.activeStreams=[];this.activeHead=0;this.incoming=new Map();this.incomingBytes=0;this.completed=new Set();this.order=[];this.buffered=0;this.rto=.2;this.srtt=null;this.rttvar=null}
 key(s,m,i){return `${s}:${m}:${i}`}; active(){return this.pending.size}
 send(stream,data){if(!Number.isInteger(stream)||stream<0||stream>=this.limits.max_streams||!Buffer.isBuffer(data)||!data.length||data.length>this.limits.max_message)throw Error('invalid message');if(this.buffered+data.length>this.limits.max_inflight||this.outgoing.size>=4096)throw Error('adapter backpressure limit reached');let m=this.next[stream];if(m===0xffffffffffffffffn)throw Error('message sequence exhausted; rekey');let size=this.codec.payload,count=Math.ceil(data.length/size);if(count>65535)throw Error('message exceeds chunk count');this.next[stream]++;if(!this.queues[stream].length)this.activeStreams.push(stream);this.queues[stream].push({message:m,data:Buffer.from(data),index:0,count});this.outgoing.set(`${stream}:${m}`,{remaining:count,bytes:data.length});this.buffered+=data.length;return this.outbound()}
 outbound(){let out=[],window=Math.min(this.limits.window_frames||this.policy[2],this.limits.max_window);while(this.pending.size<window&&this.activeHead<this.activeStreams.length){let stream=this.activeStreams[this.activeHead++],q=this.queues[stream],item=q[0],index=item.index++,start=index*this.codec.payload,payload=item.data.subarray(start,start+this.codec.payload),wire=this.codec.encode(DATA,stream,item.message,index,item.count,payload),now=this.clock();this.pending.set(this.key(stream,item.message,index),{wire,deadline:now+this.rto,attempts:0,size:payload.length,sent:now,retried:false});out.push(wire);if(item.index===item.count){item.data=null;q.shift()}if(q.length)this.activeStreams.push(stream)}if(this.activeHead===this.activeStreams.length){this.activeStreams=[];this.activeHead=0}else if(this.activeHead>1024){this.activeStreams=this.activeStreams.slice(this.activeHead);this.activeHead=0}return out}
 receive(wire){let f=this.codec.decode(wire),k=this.key(f.stream,f.message,f.index);if(f.kind===ACK){let p=this.pending.get(k);if(p){this.pending.delete(k);let mk=`${f.stream}:${f.message}`,message=this.outgoing.get(mk);if(--message.remaining===0){this.buffered-=message.bytes;this.outgoing.delete(mk)}if(!p.retried)this.sample(this.clock()-p.sent)}return {acks:[],messages:[],events:[]}}let ack=this.codec.encode(ACK,f.stream,f.message,f.index,f.count);if(f.kind===EXTENSION){let mk=`${f.stream}:${f.message}`;if(this.completed.has(mk))return {acks:[ack],messages:[],events:[]};let value=JSON.parse(f.payload.toString('utf8'));portable(value);if(!canonical(value).equals(f.payload)||Object.keys(value).sort().join(',')!=='name,value'||!this.extensions.has(value.name))throw Error('received extension is not enabled');this.remember(mk);return {acks:[ack],messages:[],events:[[f.stream,value.name,value.value]]}}let mk=`${f.stream}:${f.message}`;if(this.completed.has(mk))return {acks:[ack],messages:[],events:[]};if(!f.payload.length)throw Error('empty data chunk');if(!this.incoming.has(mk)&&this.incoming.size>=4096)throw Error('reassembly message limit reached');let state=this.incoming.get(mk)||{count:f.count,parts:new Map(),bytes:0,deadline:this.clock()+this.limits.reassembly_seconds};if(state.count!==f.count)throw Error('contradictory chunk count');if(!state.parts.has(f.index)){if(this.incomingBytes+f.payload.length>this.limits.max_inflight)throw Error('reassembly limit reached');if(state.bytes+f.payload.length>this.limits.max_message)throw Error('reassembled message is oversized');state.parts.set(f.index,f.payload);state.bytes+=f.payload.length;this.incomingBytes+=f.payload.length}this.incoming.set(mk,state);let messages=[];if(state.parts.size===f.count){let parts=[];for(let i=0;i<f.count;i++)parts.push(state.parts.get(i));let data=Buffer.concat(parts);if(data.length>this.limits.max_message)throw Error('reassembled message is oversized');messages.push([f.stream,data]);this.incoming.delete(mk);this.incomingBytes-=state.bytes;this.remember(mk)}return {acks:[ack],messages,events:[]}}
 remember(k){this.completed.add(k);this.order.push(k);if(this.order.length>4096)this.completed.delete(this.order.shift())}
 sample(rtt){if(this.srtt===null){this.srtt=rtt;this.rttvar=rtt/2}else{this.rttvar=.75*this.rttvar+.25*Math.abs(this.srtt-rtt);this.srtt=.875*this.srtt+.125*rtt}this.rto=Math.max(.05,Math.min(5,this.srtt+4*this.rttvar))}
 retransmit(){let now=this.clock(),out=[];for(let [k,p] of this.pending){if(now<p.deadline)continue;if(p.attempts>=8)throw Error(`retransmission limit reached ${k}`);p.attempts++;p.retried=true;p.deadline=now+Math.min(5,this.rto*2**p.attempts);out.push(p.wire)}for(let [k,s] of this.incoming)if(now>=s.deadline){this.incoming.delete(k);this.incomingBytes-=s.bytes}return out.concat(this.outbound())}
 extension(stream,name,value){if(!Number.isInteger(stream)||stream<0||stream>=this.limits.max_streams||!this.extensions.has(name))throw Error('extension is not enabled');let m=this.next[stream];if(m===0xffffffffffffffffn)throw Error('message sequence exhausted; rekey');this.next[stream]++;return this.codec.encode(EXTENSION,stream,m,0,1,canonical({name,value}))}
}
export class DatagramEndpoint extends EventEmitter{
 constructor(core,key,bind,peer,side=0,extensions=[]){super();if(!bind||!peer||net.isIP(bind.host)===0||net.isIP(peer.host)===0||net.isIP(bind.host)!==net.isIP(peer.host)||!Number.isInteger(bind.port)||bind.port<0||bind.port>65535||!Number.isInteger(peer.port)||peer.port<1||peer.port>65535)throw Error('invalid numeric endpoint');this.peer=peer;this.adapter=new ReliableAdapter(core,key,side,extensions);this.socket=dgram.createSocket(net.isIP(bind.host)===6?'udp6':'udp4');this.socket.on('message',(wire,info)=>{try{if(info.address!==peer.host||info.port!==peer.port)throw Error('datagram from unpinned peer');let result=this.adapter.receive(wire);for(let frame of [...result.acks,...this.adapter.outbound()])this.socket.send(frame,peer.port,peer.host);for(let item of result.messages)this.emit('data',...item);for(let event of result.events)this.emit('extension',...event)}catch(error){this.emit('adapterError',error)}});this.ready=new Promise((resolve,reject)=>{this.socket.once('error',reject);this.socket.bind(bind.port,bind.host,()=>{this.socket.off('error',reject);this.timer=setInterval(()=>{try{for(let frame of this.adapter.retransmit())this.socket.send(frame,peer.port,peer.host)}catch(error){this.emit('adapterError',error)}},50);this.timer.unref();resolve(this.socket.address())})})}
 send(stream,data){for(let frame of this.adapter.send(stream,data))this.socket.send(frame,this.peer.port,this.peer.host)}
 sendExtension(stream,name,value){this.socket.send(this.adapter.extension(stream,name,value),this.peer.port,this.peer.host)}
 close(){if(this.timer)clearInterval(this.timer);this.socket.close()}
}
// Node resolves module symlinks; argv may retain aliases such as macOS /var.
let isMain=false;
if(process.argv[1]){
 try{isMain=import.meta.url===pathToFileURL(fs.realpathSync(process.argv[1])).href;}
 catch(error){if(error.code!=='ENOENT' && error.code!=='ENOTDIR')throw error;}
}
if(isMain){let action=process.argv[2]||'catalog';if(action==='catalog')console.log(JSON.stringify({schema:'shadow6.network-adapter-catalog.v1',backend:'node',cores:POLICIES},null,2));else if(action==='decode-vector'){let x=JSON.parse(fs.readFileSync(0,'utf8')),c=new Codec(Buffer.from(x.key,'hex'),x.payload,x.side),r=c.decode(Buffer.from(x.frame,'hex'));console.log(JSON.stringify({...r,message:r.message.toString(),payload:r.payload.toString('hex')}))}else if(action==='encode-vector'){let x=JSON.parse(fs.readFileSync(0,'utf8')),c=new Codec(Buffer.from(x.key,'hex'),x.limit,x.side),wire=c.encode(x.kind,x.stream,BigInt(x.message),x.index,x.count,Buffer.from(x.payload,'hex'));console.log(JSON.stringify({frame:wire.toString('hex')}))}else{console.error('usage: shadow6-network-node [catalog|decode-vector|encode-vector]');process.exit(2)}}
