#!/usr/bin/env node
import crypto from 'node:crypto';
import dgram from 'node:dgram';
import fs from 'node:fs';
import net from 'node:net';
import {EventEmitter} from 'node:events';

export const POLICIES={go:['native',65536,64],rust:['native',65536,64],zig:['native',32768,64],ada:['required',448,32],d:['companion-required',1200,32],nim:['native',16384,64],cpp:['native',32768,64],pony:['required',960,32],hare:['required',896,16],carp:['required',960,16],gleam:['optional',4096,32],idris:['companion-required',1200,32]};
const MAGIC=Buffer.from('S6NA'), VERSION=1, DATA=1, ACK=2, EXTENSION=3, HEADER=32, TAG=16, MAX=16*1024*1024;
function derive(key,direction){return crypto.createHmac('sha256',key).update(Buffer.concat([Buffer.from('shadow6-network-v1:'),Buffer.from([direction])])).digest()}
function nonce(header){return crypto.createHash('sha256').update('shadow6-network-nonce-v1').update(header).digest().subarray(0,12)}
function portable(value,depth=0){if(depth>8)throw Error('extension nesting exceeds 8');if(value===null||typeof value==='boolean')return;if(typeof value==='string'){if(Buffer.byteLength(value)>1024)throw Error('extension string is oversized');return}if(typeof value==='number'){if(!Number.isSafeInteger(value))throw Error('extension integer is not portable');return}if(Array.isArray(value)){if(value.length>64)throw Error('extension array is oversized');value.forEach(x=>portable(x,depth+1));return}if(typeof value==='object'){let keys=Object.keys(value);if(keys.length>64)throw Error('extension object is oversized');keys.forEach(k=>{portable(k,depth+1);portable(value[k],depth+1)});return}throw Error('extension contains a nonportable value')}
function canonical(value){portable(value);let sort=x=>Array.isArray(x)?x.map(sort):(x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x);let out=Buffer.from(JSON.stringify(sort(value)));if(out.length>4096)throw Error('extension payload exceeds 4 KiB');return out}
export function loadKey(path){let before=fs.lstatSync(path);if(!before.isFile()||before.isSymbolicLink()||before.uid!==process.geteuid()||(before.mode&0o777)!==0o600||before.size!==32)throw Error('adapter key must be an owned 32-byte mode-0600 regular file');let fd=fs.openSync(path,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW|fs.constants.O_CLOEXEC);try{let opened=fs.fstatSync(fd,{bigint:true}),data=Buffer.alloc(33),count=fs.readSync(fd,data,0,33,0),after=fs.fstatSync(fd,{bigint:true});if(count!==32||opened.dev!==BigInt(before.dev)||opened.ino!==BigInt(before.ino)||after.size!==opened.size||after.mtimeNs!==opened.mtimeNs)throw Error('adapter key changed while reading');return data.subarray(0,32)}finally{fs.closeSync(fd)}}
export class Codec{
 constructor(key,payload,side=0){if(!Buffer.isBuffer(key)||key.length!==32)throw Error('adapter key must be 32 bytes');if(!Number.isInteger(payload)||payload<64||payload>65536)throw Error('invalid adapter payload');if(side!==0&&side!==1)throw Error('invalid side');this.tx=derive(key,side);this.rx=derive(key,1-side);this.payload=payload}
 encode(kind,stream,message,index,count,payload=Buffer.alloc(0)){if(![DATA,ACK,EXTENSION].includes(kind)||!Number.isInteger(stream)||stream<0||stream>=64||message<0n||message>0xffffffffffffffffn)throw Error('invalid frame identity');if(!Buffer.isBuffer(payload)||payload.length>this.payload||count<1||count>65535||index<0||index>=count)throw Error('invalid frame bounds');let h=Buffer.alloc(HEADER);MAGIC.copy(h);h.writeUInt8(VERSION,4);h.writeUInt8(kind,5);h.writeBigUInt64BE(BigInt(stream),8);h.writeBigUInt64BE(message,16);h.writeUInt16BE(index,24);h.writeUInt16BE(count,26);h.writeUInt32BE(payload.length,28);let c=crypto.createCipheriv('chacha20-poly1305',this.tx,nonce(h),{authTagLength:16});c.setAAD(h,{plaintextLength:payload.length});let body=Buffer.concat([c.update(payload),c.final(),c.getAuthTag()]);return Buffer.concat([h,body])}
 decode(wire){if(!Buffer.isBuffer(wire)||wire.length<HEADER+TAG||wire.length>HEADER+this.payload+TAG)throw Error('invalid frame size');let h=wire.subarray(0,HEADER),kind=h[5],stream=h.readBigUInt64BE(8),message=h.readBigUInt64BE(16),index=h.readUInt16BE(24),count=h.readUInt16BE(26),length=h.readUInt32BE(28);if(!h.subarray(0,4).equals(MAGIC)||h[4]!==VERSION||h.readUInt16BE(6)!==0||![DATA,ACK,EXTENSION].includes(kind)||length!==wire.length-HEADER-TAG||stream>=64n||count<1||index>=count)throw Error('invalid frame header');let body=wire.subarray(HEADER,-TAG),tag=wire.subarray(-TAG),d=crypto.createDecipheriv('chacha20-poly1305',this.rx,nonce(h),{authTagLength:16});d.setAAD(h,{plaintextLength:body.length});d.setAuthTag(tag);let payload;try{payload=Buffer.concat([d.update(body),d.final()])}catch{throw Error('frame authentication failed')}if(kind===ACK&&payload.length)throw Error('invalid acknowledgment');return {kind,stream:Number(stream),message,index,count,payload}}
}
export class ReliableAdapter{
 constructor(core,key,side=0,extensions=[]){if(!(core in POLICIES))throw Error('unknown core');this.policy=POLICIES[core];this.codec=new Codec(key,this.policy[1],side);this.extensions=new Set(extensions);if(this.extensions.size!==extensions.length||this.extensions.size>16||extensions.some(x=>typeof x!=='string'||x.length<1||x.length>64))throw Error('invalid extension allowlist');this.next=Array(64).fill(0n);this.pending=new Map();this.queues=Array.from({length:64},()=>[]);this.cursor=0;this.incoming=new Map();this.completed=new Set();this.order=[];this.buffered=0;this.rto=.2;this.srtt=null;this.rttvar=null}
 key(s,m,i){return `${s}:${m}:${i}`}; active(){return this.pending.size}
 send(stream,data){if(!Number.isInteger(stream)||stream<0||stream>=64||!Buffer.isBuffer(data)||!data.length||data.length>MAX)throw Error('invalid message');if(this.buffered+data.length>MAX)throw Error('adapter backpressure limit reached');let m=this.next[stream];if(m===0xffffffffffffffffn)throw Error('message sequence exhausted; rekey');this.next[stream]++;let count=Math.ceil(data.length/this.policy[1]);for(let i=0;i<count;i++){let p=data.subarray(i*this.policy[1],(i+1)*this.policy[1]),w=this.codec.encode(DATA,stream,m,i,count,p);this.queues[stream].push([this.key(stream,m,i),w,p.length])}this.buffered+=data.length;return this.outbound()}
 outbound(){let out=[],empty=0;while(this.pending.size<this.policy[2]&&empty<64){let q=this.queues[this.cursor];if(q.length){let [k,w,n]=q.shift(),now=performance.now()/1000;this.pending.set(k,{wire:w,deadline:now+this.rto,attempts:0,size:n,sent:now,retried:false});out.push(w);empty=0}else empty++;this.cursor=(this.cursor+1)%64}return out}
 receive(wire){let f=this.codec.decode(wire),k=this.key(f.stream,f.message,f.index);if(f.kind===ACK){let p=this.pending.get(k);if(p){this.pending.delete(k);this.buffered-=p.size;if(!p.retried)this.sample(performance.now()/1000-p.sent)}return {acks:[],messages:[],events:[]}}let ack=this.codec.encode(ACK,f.stream,f.message,f.index,f.count);if(f.kind===EXTENSION){let mk=`${f.stream}:${f.message}`;if(this.completed.has(mk))return {acks:[ack],messages:[],events:[]};let value=JSON.parse(f.payload.toString('utf8'));portable(value);if(!canonical(value).equals(f.payload)||Object.keys(value).sort().join(',')!=='name,value'||!this.extensions.has(value.name))throw Error('received extension is not enabled');this.remember(mk);return {acks:[ack],messages:[],events:[[f.stream,value.name,value.value]]}}let mk=`${f.stream}:${f.message}`;if(this.completed.has(mk))return {acks:[ack],messages:[],events:[]};let state=this.incoming.get(mk)||{count:f.count,parts:new Map(),bytes:0,deadline:performance.now()/1000+30};if(state.count!==f.count)throw Error('contradictory chunk count');if(!state.parts.has(f.index)){if([...this.incoming.values()].reduce((n,x)=>n+x.bytes,0)+f.payload.length>MAX)throw Error('reassembly limit reached');state.parts.set(f.index,f.payload);state.bytes+=f.payload.length}this.incoming.set(mk,state);let messages=[];if(state.parts.size===f.count){let parts=[];for(let i=0;i<f.count;i++)parts.push(state.parts.get(i));messages.push([f.stream,Buffer.concat(parts)]);this.incoming.delete(mk);this.remember(mk)}return {acks:[ack],messages,events:[]}}
 remember(k){this.completed.add(k);this.order.push(k);if(this.order.length>4096)this.completed.delete(this.order.shift())}
 sample(rtt){if(this.srtt===null){this.srtt=rtt;this.rttvar=rtt/2}else{this.rttvar=.75*this.rttvar+.25*Math.abs(this.srtt-rtt);this.srtt=.875*this.srtt+.125*rtt}this.rto=Math.max(.05,Math.min(5,this.srtt+4*this.rttvar))}
 retransmit(){let now=performance.now()/1000,out=[];for(let [k,p] of this.pending){if(now<p.deadline)continue;if(p.attempts>=8)throw Error(`retransmission limit reached ${k}`);p.attempts++;p.retried=true;p.deadline=now+Math.min(5,this.rto*2**p.attempts);out.push(p.wire)}for(let [k,s] of this.incoming)if(now>=s.deadline)this.incoming.delete(k);return out.concat(this.outbound())}
 extension(stream,name,value){if(!Number.isInteger(stream)||stream<0||stream>=64||!this.extensions.has(name))throw Error('extension is not enabled');let m=this.next[stream];if(m===0xffffffffffffffffn)throw Error('message sequence exhausted; rekey');this.next[stream]++;return this.codec.encode(EXTENSION,stream,m,0,1,canonical({name,value}))}
}
export class DatagramEndpoint extends EventEmitter{
 constructor(core,key,bind,peer,side=0,extensions=[]){super();if(!bind||!peer||net.isIP(bind.host)===0||net.isIP(peer.host)===0||net.isIP(bind.host)!==net.isIP(peer.host)||!Number.isInteger(bind.port)||bind.port<0||bind.port>65535||!Number.isInteger(peer.port)||peer.port<1||peer.port>65535)throw Error('invalid numeric endpoint');this.peer=peer;this.adapter=new ReliableAdapter(core,key,side,extensions);this.socket=dgram.createSocket(net.isIP(bind.host)===6?'udp6':'udp4');this.socket.on('message',(wire,info)=>{try{if(info.address!==peer.host||info.port!==peer.port)throw Error('datagram from unpinned peer');let result=this.adapter.receive(wire);for(let frame of [...result.acks,...this.adapter.outbound()])this.socket.send(frame,peer.port,peer.host);for(let item of result.messages)this.emit('data',...item);for(let event of result.events)this.emit('extension',...event)}catch(error){this.emit('adapterError',error)}});this.ready=new Promise((resolve,reject)=>{this.socket.once('error',reject);this.socket.bind(bind.port,bind.host,()=>{this.socket.off('error',reject);this.timer=setInterval(()=>{try{for(let frame of this.adapter.retransmit())this.socket.send(frame,peer.port,peer.host)}catch(error){this.emit('adapterError',error)}},50);this.timer.unref();resolve(this.socket.address())})})}
 send(stream,data){for(let frame of this.adapter.send(stream,data))this.socket.send(frame,this.peer.port,this.peer.host)}
 sendExtension(stream,name,value){this.socket.send(this.adapter.extension(stream,name,value),this.peer.port,this.peer.host)}
 close(){if(this.timer)clearInterval(this.timer);this.socket.close()}
}
if(import.meta.url===`file://${process.argv[1]}`){let action=process.argv[2]||'catalog';if(action==='catalog')console.log(JSON.stringify({schema:'shadow6.network-adapter-catalog.v1',backend:'node',cores:POLICIES},null,2));else if(action==='decode-vector'){let x=JSON.parse(fs.readFileSync(0,'utf8')),c=new Codec(Buffer.from(x.key,'hex'),x.payload,x.side),r=c.decode(Buffer.from(x.frame,'hex'));console.log(JSON.stringify({...r,message:r.message.toString(),payload:r.payload.toString('hex')}))}else if(action==='encode-vector'){let x=JSON.parse(fs.readFileSync(0,'utf8')),c=new Codec(Buffer.from(x.key,'hex'),x.limit,x.side),wire=c.encode(x.kind,x.stream,BigInt(x.message),x.index,x.count,Buffer.from(x.payload,'hex'));console.log(JSON.stringify({frame:wire.toString('hex')}))}else{console.error('usage: shadow6-network-node [catalog|decode-vector|encode-vector]');process.exit(2)}}
