with Interfaces.C; with System;
package Native with SPARK_Mode => Off is
   subtype Int is Interfaces.C.int;
   subtype Time is Interfaces.C.long_long;
   function Init return Int with Import, Convention => C, External_Name => "s6_init";
   function Level return Int with Import, Convention => C, External_Name => "s6_level";
   function Random (P : System.Address; N : Int) return Int with Import, Convention => C, External_Name => "s6_random";
   function Keypair (Seed, Pub, Secret : System.Address) return Int with Import, Convention => C, External_Name => "s6_keypair";
   function Sign (Secret, Data : System.Address; N : Int; Sig : System.Address) return Int with Import, Convention => C, External_Name => "s6_sign";
   function Verify (Pub, Data : System.Address; N : Int; Sig : System.Address) return Int with Import, Convention => C, External_Name => "s6_verify";
   function Xpublic (Secret, Pub : System.Address) return Int with Import, Convention => C, External_Name => "s6_xpublic";
   function Shared (Secret, Pub, Key : System.Address) return Int with Import, Convention => C, External_Name => "s6_shared";
   function Hash (P : System.Address; N : Int; Out_P : System.Address; SHA1 : Int := 0) return Int with Import, Convention => C, External_Name => "s6_hash";
   procedure Wipe (P : System.Address; N : Int) with Import, Convention => C, External_Name => "s6_wipe";
   function Seal (Key : System.Address; Seq : Int; Plain, Wire : System.Address) return Int with Import, Convention => C, External_Name => "s6_seal";
   function Open_Cell (Key : System.Address; Seq : Int; Wire, Plain : System.Address) return Int with Import, Convention => C, External_Name => "s6_open";
   function File_Read (Path : String; P : System.Address; N : Int) return Int with Import, Convention => C, External_Name => "s6_file";
   function Replay (Path : String; Digest : System.Address; Now : Time) return Int with Import, Convention => C, External_Name => "s6_replay";
   function Now return Time with Import, Convention => C, External_Name => "s6_now";
   function Clock return Time with Import, Convention => C, External_Name => "s6_clock";
   function Listen (Host : String; Port : Int) return Int with Import, Convention => C, External_Name => "s6_listen";
   function Connect (Host : String; Port : Int) return Int with Import, Convention => C, External_Name => "s6_connect";
   function Accept_Peer (H : Int) return Int with Import, Convention => C, External_Name => "s6_accept";
   procedure Close (H : Int) with Import, Convention => C, External_Name => "s6_close";
   function Port (H : Int) return Int with Import, Convention => C, External_Name => "s6_port";
   function IP (H : Int; Out_P : System.Address; Peer : Int) return Int with Import, Convention => C, External_Name => "s6_ip";
   function TLS (H : Int; Host, Cert, Key : String) return Int with Import, Convention => C, External_Name => "s6_tls";
   function Read (H : Int; P : System.Address; N : Int; Exact : Int := 1) return Int with Import, Convention => C, External_Name => "s6_read";
   function Write (H : Int; P : System.Address; N : Int) return Int with Import, Convention => C, External_Name => "s6_write";
   function Ready (H : Int) return Int with Import, Convention => C, External_Name => "s6_ready";
   procedure Pause with Import, Convention => C, External_Name => "s6_pause";
   procedure Half_Close (H : Int) with Import, Convention => C, External_Name => "s6_half_close";
end Native;
