#!/usr/bin/env python3
"""Generate dependency-free NFC tables for independently compiled JSON readers.

Only Unicode canonical decompositions/compositions and combining classes are
used. Hangul is algorithmic. Generated readers share syntax vocabulary, never
Core wire formats or lifecycle authority. Regenerate explicitly with Python's
Unicode database; no dependency download or runtime lookup occurs.
"""
from pathlib import Path
import unicodedata as ud

ROOT=Path(__file__).resolve().parents[1]


def tables():
    decompositions={};classes={};compositions={}
    for point in range(0x110000):
        character=chr(point);parts=ud.decomposition(character)
        if parts and not parts.startswith('<'):
            value=[int(x,16) for x in parts.split()];decompositions[point]=value
            if len(value)==2 and ud.normalize('NFC',''.join(map(chr,value)))==character:
                compositions[(value[0]<<21)|value[1]]=point
        ccc=ud.combining(character)
        if ccc:classes[point]=ccc
    return decompositions,classes,compositions


def generate():
    decomp,ccc,compose=tables();note=f'Generated by Tools/generate_unicode_nfc.py; Unicode {ud.unidata_version}. '
    go='// '+note+'Do not hand edit.\npackage main\n\nimport "sort"\n\n'
    go+='var nfcDecomposition = map[rune][]rune{\n'+''.join(f'{k}: {{{",".join(map(str,v))}}},\n' for k,v in decomp.items())+'}\n'
    go+='var nfcClass = map[rune]int{\n'+''.join(f'{k}: {v},\n' for k,v in ccc.items())+'}\n'
    go+='var nfcComposition = map[uint64]rune{\n'+''.join(f'{k}: {v},\n' for k,v in sorted(compose.items()))+'}\n'
    go+='''
func unicodeNFC(text string) bool {
 ascii:=true;for _,c:=range text {if c>=128 {ascii=false;break}};if ascii{return true}
 original:=[]rune(text);decomposed:=make([]rune,0,len(original));var expand func(rune)
 expand=func(c rune) {if c>=0xac00&&c<0xd7a4 {s:=c-0xac00;expand(0x1100+s/588);expand(0x1161+(s%588)/28);if s%28!=0 {expand(0x11a7+s%28)};return};if parts,ok:=nfcDecomposition[c];ok {for _,v:=range parts {expand(v)};return};decomposed=append(decomposed,c)}
 for _,c:=range original {expand(c)}
 order:=func(start,end int){part:=decomposed[start:end];sort.SliceStable(part,func(i,j int)bool{return nfcClass[part[i]]<nfcClass[part[j]]})};start:=0;for i,c:=range decomposed {if nfcClass[c]==0 {order(start,i);start=i+1}};order(start,len(decomposed))
 result:=make([]rune,0,len(decomposed));starter:=-1;last:=0
 for _,c:=range decomposed {class:=nfcClass[c];combined:=rune(0);if starter>=0&&(last<class||last==0) {left:=result[starter];if left>=0x1100&&left<=0x1112&&c>=0x1161&&c<=0x1175 {combined=0xac00+(left-0x1100)*588+(c-0x1161)*28} else if left>=0xac00&&left<0xd7a4&&(left-0xac00)%28==0&&c>0x11a7&&c<=0x11c2 {combined=left+c-0x11a7} else {combined=nfcComposition[(uint64(left)<<21)|uint64(c)]}}
 if combined!=0 {result[starter]=combined;continue};if class==0 {starter=len(result)};result=append(result,c);last=class}
 if len(result)!=len(original){return false};for i,c:=range result {if c!=original[i]{return false}};return true
}
'''
    for target in ('Core-Go/unicode_nfc.go','Gate/unicode_nfc.go'):(ROOT/target).write_text(go)
    # Sparse sorted tables keep native readers independent of external Unicode libraries.
    rust='// '+note+'Do not hand edit.\n'
    rust+='const DECOMP: &[(u32, &[u32])] = &[\n'+''.join(f'({k}, &[{",".join(map(str,v))}]),\n' for k,v in decomp.items())+'];\n'
    rust+='const CLASS: &[(u32, u32)] = &[\n'+''.join(f'({k}, {v}),\n' for k,v in ccc.items())+'];\n'
    rust+='const COMPOSE: &[(u64, u32)] = &[\n'+''.join(f'({k}, {v}),\n' for k,v in sorted(compose.items()))+'];\n'
    rust+='''
fn class(c:u32)->u32 {CLASS.binary_search_by_key(&c,|x|x.0).map(|i|CLASS[i].1).unwrap_or(0)}
fn expand(c:u32,out:&mut Vec<u32>) {if (0xac00..0xd7a4).contains(&c) {let s=c-0xac00;expand(0x1100+s/588,out);expand(0x1161+(s%588)/28,out);if !s.is_multiple_of(28) {expand(0x11a7+s%28,out)};return}if let Ok(i)=DECOMP.binary_search_by_key(&c,|x|x.0) {for v in DECOMP[i].1 {expand(*v,out)};return}out.push(c)}
pub fn is_nfc(text:&str)->bool {if text.is_ascii(){return true}let original:Vec<u32>=text.chars().map(|c|c as u32).collect();let mut decomposed=Vec::new();for c in &original {expand(*c,&mut decomposed)}let mut start=0;for i in 0..decomposed.len(){if class(decomposed[i])==0{decomposed[start..i].sort_by_key(|c|class(*c));start=i+1}}decomposed[start..].sort_by_key(|c|class(*c));let mut result:Vec<u32>=Vec::new();let mut starter=None;let mut last=0;for c in decomposed {let cc=class(c);let mut combined=0;if let Some(i)=starter {if last<cc||last==0 {let left:u32=result[i];if (0x1100..=0x1112).contains(&left)&&(0x1161..=0x1175).contains(&c) {combined=0xac00+(left-0x1100)*588+(c-0x1161)*28} else if (0xac00..0xd7a4).contains(&left)&&(left-0xac00).is_multiple_of(28)&&(0x11a8..=0x11c2).contains(&c) {combined=left+c-0x11a7} else if let Ok(index)=COMPOSE.binary_search_by_key(&(((left as u64)<<21)|c as u64),|x|x.0) {combined=COMPOSE[index].1}}}if combined!=0 {result[starter.unwrap()]=combined;continue}if cc==0 {starter=Some(result.len())}result.push(c);last=cc}result==original}
'''
    (ROOT/'Core-Rust/src/unicode_nfc.rs').write_text(rust)
    cpp='// '+note+'Do not hand edit.\n#pragma once\n#include <string_view>\n#include <vector>\n#include <cstdint>\n#include <algorithm>\n#include <iterator>\nnamespace shadow6 {\n'
    assert all(len(value)<=2 for value in decomp.values())
    cpp+='struct NfcDecomposition{std::uint32_t point,first,second;};\ninline constexpr NfcDecomposition nfc_decomposition[]={\n'+''.join(f'{{{k},{v[0]},{v[1] if len(v)>1 else 0}}},\n' for k,v in decomp.items())+'};\n'
    cpp+='struct NfcClass{std::uint32_t point;unsigned value;};\ninline constexpr NfcClass nfc_classes[]={\n'+''.join(f'{{{k},{v}}},\n' for k,v in ccc.items())+'};\n'
    cpp+='struct NfcComposition{std::uint64_t point;std::uint32_t value;};\ninline constexpr NfcComposition nfc_composition[]={\n'+''.join(f'{{{k}ULL,{v}}},\n' for k,v in sorted(compose.items()))+'};\n'
    cpp+='''
inline unsigned nfc_class(std::uint32_t c){auto i=std::lower_bound(std::begin(nfc_classes),std::end(nfc_classes),c,[](auto row,auto key){return row.point<key;});return i==std::end(nfc_classes)||i->point!=c?0:i->value;}
inline void nfc_expand(std::uint32_t c,std::vector<std::uint32_t>&out){if(c>=0xac00&&c<0xd7a4){auto s=c-0xac00;nfc_expand(0x1100+s/588,out);nfc_expand(0x1161+(s%588)/28,out);if(s%28)nfc_expand(0x11a7+s%28,out);return;}auto i=std::lower_bound(std::begin(nfc_decomposition),std::end(nfc_decomposition),c,[](auto row,auto key){return row.point<key;});if(i!=std::end(nfc_decomposition)&&i->point==c){nfc_expand(i->first,out);if(i->second)nfc_expand(i->second,out);return;}out.push_back(c);}
inline bool unicode_nfc(std::string_view text){std::vector<std::uint32_t>original;for(std::size_t i=0;i<text.size();){auto c=static_cast<unsigned char>(text[i++]);unsigned n=0,value=c;if(c>=0xf0){n=3;value=c&7;}else if(c>=0xe0){n=2;value=c&15;}else if(c>=0xc0){n=1;value=c&31;}for(unsigned j=0;j<n;++j){if(i>=text.size())return false;value=(value<<6)|(static_cast<unsigned char>(text[i++])&63);}original.push_back(value);}if(std::all_of(original.begin(),original.end(),[](auto c){return c<128;}))return true;std::vector<std::uint32_t>decomposed,result;for(auto c:original)nfc_expand(c,decomposed);auto order=[&](std::size_t start,std::size_t end){std::stable_sort(decomposed.begin()+start,decomposed.begin()+end,[](auto a,auto b){return nfc_class(a)<nfc_class(b);});};std::size_t start=0;for(std::size_t i=0;i<decomposed.size();++i)if(nfc_class(decomposed[i])==0){order(start,i);start=i+1;}order(start,decomposed.size());std::size_t starter=0;bool has_starter=false;unsigned last=0;for(auto c:decomposed){auto cc=nfc_class(c);std::uint32_t combined=0;if(has_starter&&(last<cc||last==0)){auto left=result[starter];if(left>=0x1100&&left<=0x1112&&c>=0x1161&&c<=0x1175)combined=0xac00+(left-0x1100)*588+(c-0x1161)*28;else if(left>=0xac00&&left<0xd7a4&&(left-0xac00)%28==0&&c>0x11a7&&c<=0x11c2)combined=left+c-0x11a7;else{auto key=(static_cast<std::uint64_t>(left)<<21)|c;auto i=std::lower_bound(std::begin(nfc_composition),std::end(nfc_composition),key,[](auto row,auto value){return row.point<value;});if(i!=std::end(nfc_composition)&&i->point==key)combined=i->value;}}if(combined){result[starter]=combined;continue;}if(cc==0){starter=result.size();has_starter=true;}result.push_back(c);last=cc;}return result==original;}
}
'''
    (ROOT/'Core-Cpp/src/unicode_nfc.hpp').write_text(cpp)


if __name__=='__main__':generate()
